/**
 * CreateWatch DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AddProjectToWatchlistParams } from "@chatterisk/core/projects";

export function createCreateWatchRequest(overrides: Partial<AddProjectToWatchlistParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
