/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@chatterisk/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAggregatesDomainModule,
  buildAlertsDomainModule,
  buildCommentsDomainModule,
  buildDossiersDomainModule,
  buildExternalLinksDomainModule,
  buildIdentityDomainModule,
  buildProjectsDomainModule,
} from "../domains/index.js";
import type {
  AggregatesDomainModule,
  AlertsDomainModule,
  CommentsDomainModule,
  DossiersDomainModule,
  ExternalLinksDomainModule,
  IdentityDomainModule,
  ProjectsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private aggregatesModule: AggregatesDomainModule | null = null;
  private alertsModule: AlertsDomainModule | null = null;
  private commentsModule: CommentsDomainModule | null = null;
  private dossiersModule: DossiersDomainModule | null = null;
  private externalLinksModule: ExternalLinksDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private projectsModule: ProjectsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get aggregates domain module
   */
  getAggregatesDependencies(): AggregatesDomainModule {
    if (!this.aggregatesModule) {
      this.aggregatesModule = buildAggregatesDomainModule(this.dynamoClient);
    }
    return this.aggregatesModule;
  }

  /**
   * Get alerts domain module
   */
  getAlertsDependencies(): AlertsDomainModule {
    if (!this.alertsModule) {
      this.alertsModule = buildAlertsDomainModule(this.dynamoClient);
    }
    return this.alertsModule;
  }

  /**
   * Get comments domain module
   */
  getCommentsDependencies(): CommentsDomainModule {
    if (!this.commentsModule) {
      this.commentsModule = buildCommentsDomainModule(this.dynamoClient);
    }
    return this.commentsModule;
  }

  /**
   * Get dossiers domain module
   */
  getDossiersDependencies(): DossiersDomainModule {
    if (!this.dossiersModule) {
      this.dossiersModule = buildDossiersDomainModule(this.dynamoClient);
    }
    return this.dossiersModule;
  }

  /**
   * Get external-links domain module
   */
  getExternalLinksDependencies(): ExternalLinksDomainModule {
    if (!this.externalLinksModule) {
      this.externalLinksModule = buildExternalLinksDomainModule(this.dynamoClient);
    }
    return this.externalLinksModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get projects domain module
   */
  getProjectsDependencies(): ProjectsDomainModule {
    if (!this.projectsModule) {
      this.projectsModule = buildProjectsDomainModule(this.dynamoClient);
    }
    return this.projectsModule;
  }

  clearAggregatesDependencies(): void { this.aggregatesModule = null; }
  clearAlertsDependencies(): void { this.alertsModule = null; }
  clearCommentsDependencies(): void { this.commentsModule = null; }
  clearDossiersDependencies(): void { this.dossiersModule = null; }
  clearExternalLinksDependencies(): void { this.externalLinksModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearProjectsDependencies(): void { this.projectsModule = null; }

  getAggregatesDependenciesForRequest(): AggregatesDomainModule {
    return this.getAggregatesDependencies();
  }

  getAlertsDependenciesForRequest(): AlertsDomainModule {
    return this.getAlertsDependencies();
  }

  getCommentsDependenciesForRequest(): CommentsDomainModule {
    return this.getCommentsDependencies();
  }

  getDossiersDependenciesForRequest(): DossiersDomainModule {
    return this.getDossiersDependencies();
  }

  getExternalLinksDependenciesForRequest(): ExternalLinksDomainModule {
    return this.getExternalLinksDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getProjectsDependenciesForRequest(): ProjectsDomainModule {
    return this.getProjectsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.aggregatesModule = null;
    this.alertsModule = null;
    this.commentsModule = null;
    this.dossiersModule = null;
    this.externalLinksModule = null;
    this.identityModule = null;
    this.projectsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
