/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Aggregates Domain Use Cases
 * 
 * List of all use case names for the aggregates domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const AGGREGATES_USE_CASES = [
  "executeGetLatestAggregate",
  "executeGetPartnerRiskBadge",
  "executeListProjectAggregates"
] as const;
