/**
 * GetComment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getComment } from "@chatterisk/api-server/domains/comments/handlers";
import type { CommentsDDDDependencies } from "@chatterisk/api-server/domains/comments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { COMMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetComment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CommentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CommentsDDDDependencies>(
      COMMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetComment, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { commentId: entity.id };

    await getComment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetComment.execute).toHaveBeenCalledWith(expect.objectContaining({ commentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { commentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetComment, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getComment(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
