/**
 * Aggregates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Aggregates Domain Module - Composition root
 *
 * DDD: Composition root for aggregates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AggregateRepositoryAdapter,
  LatestRepositoryAdapter,
  RiskBadgeRepositoryAdapter,
} from "@chatterisk/adapters/aggregates";
import { getIdGeneratorService } from "@chatterisk/adapters";
import type { AdapterDynamoDBClient } from "@chatterisk/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetLatestAggregate,
  ExecuteGetPartnerRiskBadge,
  ExecuteListProjectAggregates,
} from "@chatterisk/services/aggregates/usecases";
// Ports (interfaces)
import type {
  AggregateRepository,
  LatestRepository,
  RiskBadgeRepository,
} from "@chatterisk/services/aggregates/ports";

export interface AggregatesDomainModule {
  repos: {
    aggregates: AggregateRepository;
    latests: LatestRepository;
    riskBadges: RiskBadgeRepository;
  };
  useCases: {
    aggregates: {
      list: ExecuteListProjectAggregates;
    };
    latests: {
      get: ExecuteGetLatestAggregate;
    };
    riskBadges: {
      get: ExecuteGetPartnerRiskBadge;
    };
  };
}

export function buildAggregatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AggregatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      aggregates?: AggregateRepository;
      latests?: LatestRepository;
      riskBadges?: RiskBadgeRepository;
    } = {};

    obj.aggregates = new AggregateRepositoryAdapter(dynamoClient);
    obj.latests = new LatestRepositoryAdapter(dynamoClient);
    obj.riskBadges = new RiskBadgeRepositoryAdapter(dynamoClient);
    return {
      aggregates: obj.aggregates!,
      latests: obj.latests!,
      riskBadges: obj.riskBadges!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    aggregates: {
      list: new ExecuteListProjectAggregates(executionContext, idGenerator, repos.aggregates),
    },
    latests: {
      get: new ExecuteGetLatestAggregate(executionContext, idGenerator, repos.latests),
    },
    riskBadges: {
      get: new ExecuteGetPartnerRiskBadge(executionContext, idGenerator, repos.riskBadges),
    },
  };
  return { repos, useCases: useCases as AggregatesDomainModule["useCases"] };
}
