/**
 * ProjectRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProjectRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProjectRepository,
} from "@chatterisk/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProjectRepositoryDdb } from "./project-repository.ddb.js";

/**
 * ProjectRepositoryAdapter
 *
 * Implements ProjectRepository port for infrastructure layer.
 */
export class ProjectRepositoryAdapter implements ProjectRepository {
  private readonly ddb: ProjectRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProjectRepositoryDdb(this.dynamoClient);
  }

  async listRiskProjects(input: Parameters<ProjectRepository['listRiskProjects']>[0]): Promise<Awaited<ReturnType<ProjectRepository['listRiskProjects']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRiskProjects(input);
  }

  async registerRiskProject(input: Parameters<ProjectRepository['registerRiskProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['registerRiskProject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerRiskProject(input);
  }

  async getRiskProject(input: Parameters<ProjectRepository['getRiskProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['getRiskProject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRiskProject(input);
  }

  async updateRiskProject(input: Parameters<ProjectRepository['updateRiskProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['updateRiskProject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateRiskProject(input);
  }
}
