/**
 * WatchRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WatchRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WatchRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WatchRepository,
} from "@chatterisk/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WatchRepositoryDdb } from "./watch-repository.ddb.js";

/**
 * WatchRepositoryAdapter
 *
 * Implements WatchRepository port for infrastructure layer.
 */
export class WatchRepositoryAdapter implements WatchRepository {
  private readonly ddb: WatchRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WatchRepositoryDdb(this.dynamoClient);
  }

  async addProjectToWatchlist(input: Parameters<WatchRepository['addProjectToWatchlist']>[0]): Promise<Awaited<ReturnType<WatchRepository['addProjectToWatchlist']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.addProjectToWatchlist(input);
  }

  async removeProjectFromWatchlist(input: Parameters<WatchRepository['removeProjectFromWatchlist']>[0]): Promise<Awaited<ReturnType<WatchRepository['removeProjectFromWatchlist']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.removeProjectFromWatchlist(input);
  }
}
