/**
 * Latest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Latest DTOs
 *
 * DDD: Application DTOs for Latest use cases.
 */

import type { GetLatestAggregateParams } from "@chatterisk/core/aggregates/types";

export type GetLatestAggregateInput = GetLatestAggregateParams;

export type GetLatestAggregateOutput = {};
