/**
 * RiskBadge DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskBadge DTOs
 *
 * DDD: Application DTOs for RiskBadge use cases.
 */

import type { GetPartnerRiskBadgeParams } from "@chatterisk/core/aggregates/types";

export type GetPartnerRiskBadgeInput = GetPartnerRiskBadgeParams;

export type GetPartnerRiskBadgeOutput = {};
