/**
 * ProjectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepository Port
 *
 * DDD: Application port for projectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRiskProjectInput, GetRiskProjectOutput, ListRiskProjectsInput, ListRiskProjectsOutput, RegisterRiskProjectInput, RegisterRiskProjectOutput, UpdateRiskProjectInput, UpdateRiskProjectOutput } from "../dto/project.dto";
export interface ProjectRepository {
  listRiskProjects(input: ListRiskProjectsInput): Promise<ListRiskProjectsOutput>;
  registerRiskProject(input: RegisterRiskProjectInput): Promise<RegisterRiskProjectOutput>;
  getRiskProject(input: GetRiskProjectInput): Promise<GetRiskProjectOutput>;
  updateRiskProject(input: UpdateRiskProjectInput): Promise<UpdateRiskProjectOutput>;
}

export type { GetRiskProjectInput, GetRiskProjectOutput, ListRiskProjectsInput, ListRiskProjectsOutput, RegisterRiskProjectInput, RegisterRiskProjectOutput, UpdateRiskProjectInput, UpdateRiskProjectOutput } from "../dto/project.dto";
