/**
 * Routes for Aggregate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listProjectAggregates } from "../handlers/aggregate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function aggregateRoutes(fastify: FastifyInstance) {
  // GET /v1/projects/{projectId}/aggregates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/projects/:projectId/aggregates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAggregatesDependenciesForRequest();
        await listProjectAggregates(request, reply, deps);
      });
    }
  );


}
