/**
 * Routes for Latest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLatestAggregate } from "../handlers/latest.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function latestRoutes(fastify: FastifyInstance) {
  // GET /v1/aggregates/latest (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/aggregates/latest",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAggregatesDependenciesForRequest();
        await getLatestAggregate(request, reply, deps);
      });
    }
  );


}
