/**
 * GetRiskProject handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRiskProject } from "@chatterisk/api-server/domains/projects/handlers";
import type { ProjectsDDDDependencies } from "@chatterisk/api-server/domains/projects";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { PROJECTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRiskProject", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProjectsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProjectsDDDDependencies>(
      PROJECTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRiskProject, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { projectId: entity.id };

    await getRiskProject(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRiskProject.execute).toHaveBeenCalledWith(expect.objectContaining({ projectId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { projectId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRiskProject, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRiskProject(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
