/**
 * ExecuteCreateAlertPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAlertPolicy Use Case
 *
 * DDD: Application use case for create AlertPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAlertPolicyInput, CreateAlertPolicyOutput } from "../dto/alert-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { AlertPolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAlertPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alertPolicy: AlertPolicyRepository
  ) {}

  async execute(input: CreateAlertPolicyInput): Promise<CreateAlertPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec: routing, threshold, window, workspaceId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.workspaceId) {
      throw new ValidationError("workspaceId is required");
    }
    if (!input.threshold) {
      throw new ValidationError("threshold is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (alerts domain)
    const entityId = this.idGenerator.altId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.alertPolicy.createAlertPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAlertPolicyOutput;
  }
}
