/**
 * ExecuteUpdateAlertPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateAlertPolicy Use Case
 *
 * DDD: Application use case for update AlertPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateAlertPolicyInput, UpdateAlertPolicyOutput } from "../dto/alert-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { AlertPolicyRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateAlertPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alertPolicy: AlertPolicyRepository
  ) {}

  async execute(input: UpdateAlertPolicyInput): Promise<UpdateAlertPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load existing entity
    const existing = await this.alertPolicy.getAlertPolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.alertPolicy.updateAlertPolicy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateAlertPolicyOutput;
  }
}
