/**
 * ExecuteListAlertPolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAlertPolicies Use Case
 *
 * DDD: Application use case for list AlertPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAlertPoliciesInput, ListAlertPoliciesOutput } from "../dto/alert-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { AlertPolicyRepository } from "../ports";

export class ExecuteListAlertPolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alertPolicy: AlertPolicyRepository
  ) {}

  async execute(input: ListAlertPoliciesInput): Promise<ListAlertPoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.alertPolicy.listAlertPolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAlertPoliciesOutput;
  }
}
