/**
 * ExecuteSnoozeAlert - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSnoozeAlert Use Case
 *
 * DDD: Application use case for get Snooze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SnoozeAlertInput, SnoozeAlertOutput } from "../dto/snooze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { SnoozeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSnoozeAlert {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly snooze: SnoozeRepository
  ) {}

  async execute(input: SnoozeAlertInput): Promise<SnoozeAlertOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec: note, until
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).alertId) {
      throw new ValidationError("alertId is required");
    }
    const alertId = (input as any).alertId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.snooze.snoozeAlert({ alertId: alertId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${alertId}`);
    }

    return entity as SnoozeAlertOutput;
  }
}
