/**
 * ExecuteGetAlertPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAlertPolicy Use Case
 *
 * DDD: Application use case for get AlertPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAlertPolicyInput, GetAlertPolicyOutput } from "../dto/alert-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { AlertPolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAlertPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alertPolicy: AlertPolicyRepository
  ) {}

  async execute(input: GetAlertPolicyInput): Promise<GetAlertPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.altId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.alertPolicy.getAlertPolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }

    return entity as GetAlertPolicyOutput;
  }
}
