/**
 * RemoveProjectFromWatchlist handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { removeProjectFromWatchlist } from "@chatterisk/api-server/domains/projects/handlers";
import type { ProjectsDDDDependencies } from "@chatterisk/api-server/domains/projects";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { PROJECTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RemoveProjectFromWatchlist", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProjectsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProjectsDDDDependencies>(
      PROJECTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 on successful deletion", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    mockRequest.params = { projectId: entity.id };
    
    vi.spyOn(mockDeps.executeRemoveProjectFromWatchlist, "execute").mockResolvedValue(undefined);

    await removeProjectFromWatchlist(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRemoveProjectFromWatchlist.execute).toHaveBeenCalledWith(expect.objectContaining({ projectId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
  });

});
