/**
 * ExecuteGetExternalLink - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetExternalLink Use Case
 *
 * DDD: Application use case for get ExternalLink.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetExternalLinkInput, GetExternalLinkOutput } from "../dto/external-link.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { ExternalLinkRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetExternalLink {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly externalLink: ExternalLinkRepository
  ) {}

  async execute(input: GetExternalLinkInput): Promise<GetExternalLinkOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lnkId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).linkId) {
      throw new ValidationError("linkId is required");
    }
    const linkId = (input as any).linkId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.externalLink.getExternalLink({ linkId: linkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${linkId}`);
    }

    return entity as GetExternalLinkOutput;
  }
}
