/**
 * ExecuteDeleteExternalLink - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeleteExternalLink Use Case
 *
 * DDD: Application use case for delete ExternalLink.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeleteExternalLinkInput, DeleteExternalLinkOutput } from "../dto/external-link.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { ExternalLinkRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanDelete } from "../policies/can-delete.policy";
export class ExecuteDeleteExternalLink {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly externalLink: ExternalLinkRepository
  ) {}

  async execute(input: DeleteExternalLinkInput): Promise<DeleteExternalLinkOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lnkId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).linkId) {
      throw new ValidationError("linkId is required");
    }
    const linkId = (input as any).linkId;

    // Load existing entity
    const existing = await this.externalLink.getExternalLink({ linkId: linkId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${linkId}`);
    }
    // Check policy
    if (!CanDelete.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Delete entity via repository (pass correlation ID for response meta)
    await this.externalLink.deleteExternalLink({ linkId: linkId, orgId: this.context.getOrgId(), correlationId } as any);

    return {} as DeleteExternalLinkOutput;
  }
}
