/**
 * Watch DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Watch DTOs
 *
 * DDD: Application DTOs for Watch use cases.
 */

import type { AddProjectToWatchlistParams, RemoveProjectFromWatchlistParams } from "@chatterisk/core/projects/types";

export type AddProjectToWatchlistInput = AddProjectToWatchlistParams;

export type RemoveProjectFromWatchlistInput = RemoveProjectFromWatchlistParams;

export type AddProjectToWatchlistOutput = {};

export type RemoveProjectFromWatchlistOutput = {};
