/**
 * Routes for BotRuling
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { applyCommentBotRuling, listBotRulings } from "../handlers/bot-ruling.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function botRulingRoutes(fastify: FastifyInstance) {
  // GET /v1/bot-rulings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/bot-rulings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await listBotRulings(request, reply, deps);
      });
    }
  );


  // POST /v1/comments/{commentId}/bot-ruling (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/comments/:commentId/bot-ruling",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { commentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await applyCommentBotRuling(request, reply, deps);
      });
    }
  );


}
