/**
 * Routes for Comment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getComment, ingestComment, listProjectComments } from "../handlers/comment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function commentRoutes(fastify: FastifyInstance) {
  // GET /v1/comments/{commentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/comments/:commentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { commentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await getComment(request, reply, deps);
      });
    }
  );


  // POST /v1/projects/{projectId}/comments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/projects/:projectId/comments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await ingestComment(request, reply, deps);
      });
    }
  );


  // GET /v1/projects/{projectId}/comments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/projects/:projectId/comments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await listProjectComments(request, reply, deps);
      });
    }
  );


}
