/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { retentionRoutes } from "./retention.routes.js";
export { runRoutes } from "./run.routes.js";
export { botRulingRoutes } from "./bot-ruling.routes.js";
export { commentRoutes } from "./comment.routes.js";
export { redactRoutes } from "./redact.routes.js";
