/**
 * Routes for Retention
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCommentRetentionPolicy, updateCommentRetentionPolicy } from "../handlers/retention.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function retentionRoutes(fastify: FastifyInstance) {
  // GET /v1/comments/retention (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/comments/retention",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await getCommentRetentionPolicy(request, reply, deps);
      });
    }
  );


  // PUT /v1/comments/retention (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/comments/retention",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await updateCommentRetentionPolicy(request, reply, deps);
      });
    }
  );


}
