/**
 * Routes for Run
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { runCommentRetentionJob } from "../handlers/run.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function runRoutes(fastify: FastifyInstance) {
  // POST /v1/comments/retention/run (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/comments/retention/run",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCommentsDependenciesForRequest();
        await runCommentRetentionJob(request, reply, deps);
      });
    }
  );


}
