/**
 * Routes for Project
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getRiskProject, listRiskProjects, registerRiskProject, updateRiskProject } from "../handlers/project.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function projectRoutes(fastify: FastifyInstance) {
  // GET /v1/projects (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/projects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await listRiskProjects(request, reply, deps);
      });
    }
  );


  // POST /v1/projects (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/projects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await registerRiskProject(request, reply, deps);
      });
    }
  );


  // GET /v1/projects/{projectId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/projects/:projectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await getRiskProject(request, reply, deps);
      });
    }
  );


  // PATCH /v1/projects/{projectId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/projects/:projectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await updateRiskProject(request, reply, deps);
      });
    }
  );


}
