/**
 * Routes for Watch
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { addProjectToWatchlist, removeProjectFromWatchlist } from "../handlers/watch.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function watchRoutes(fastify: FastifyInstance) {
  // POST /v1/projects/{projectId}/watch (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/projects/:projectId/watch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await addProjectToWatchlist(request, reply, deps);
      });
    }
  );


  // DELETE /v1/projects/{projectId}/watch (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/projects/:projectId/watch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProjectsDependenciesForRequest();
        await removeProjectFromWatchlist(request, reply, deps);
      });
    }
  );


}
