/**
 * Handlers for ExternalLink
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ExternalLinksDomainModule } from "../dependencies/external-links-ddd.dependencies.js";
import type { CreateExternalLinkInput, DeleteExternalLinkInput, GetExternalLinkInput, ListExternalLinksInput } from "@chatterisk/services/external-links";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/external-links
 * Operation: listExternalLinks
 */
export async function listExternalLinks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], projectId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ExternalLinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListExternalLinksInput;
  const result = await deps.useCases.externalLinks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/external-links
 * Operation: createExternalLink
 */
export async function createExternalLink(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ExternalLinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as CreateExternalLinkInput;
  const result = await deps.useCases.externalLinks.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/external-links/{linkId}
 * Operation: getExternalLink
 */
export async function getExternalLink(
  request: FastifyRequest<{ Params: { linkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExternalLinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    linkId: request.params.linkId,
  } as GetExternalLinkInput;
  const result = await deps.useCases.externalLinks.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v1/external-links/{linkId}
 * Operation: deleteExternalLink
 */
export async function deleteExternalLink(
  request: FastifyRequest<{ Params: { linkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExternalLinksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    linkId: request.params.linkId,
  } as DeleteExternalLinkInput;
  const result = await deps.useCases.externalLinks.delete.execute(input);
  return reply.code(204).send(result);
}


