/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as aggregatesRoutes from "../../domains/aggregates/routes/index.js";
import * as alertsRoutes from "../../domains/alerts/routes/index.js";
import * as commentsRoutes from "../../domains/comments/routes/index.js";
import * as dossiersRoutes from "../../domains/dossiers/routes/index.js";
import * as externalLinksRoutes from "../../domains/external-links/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as projectsRoutes from "../../domains/projects/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "aggregates", mod: aggregatesRoutes },
  { domain: "alerts", mod: alertsRoutes },
  { domain: "comments", mod: commentsRoutes },
  { domain: "dossiers", mod: dossiersRoutes },
  { domain: "external-links", mod: externalLinksRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "signupRoutes", "sessionRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "projects", mod: projectsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
