/**
 * UpdateAlertPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateAlertPolicy } from "@chatterisk/api-server/domains/alerts/handlers";
import type { AlertsDDDDependencies } from "@chatterisk/api-server/domains/alerts";
import { createAlertPolicy as createAlertPolicyEntity } from "@chatterisk/factories/alerts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { ALERTS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateAlertPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AlertsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AlertsDDDDependencies>(
      ALERTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createAlertPolicyEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { policyId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateAlertPolicy, "execute").mockResolvedValue(useCaseResult);

    await updateAlertPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateAlertPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
