/**
 * AggregateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AggregateRepository Port
 *
 * DDD: Application port for aggregaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListProjectAggregatesInput, ListProjectAggregatesOutput } from "../dto/aggregate.dto";
export interface AggregateRepository {
  listProjectAggregates(input: ListProjectAggregatesInput): Promise<ListProjectAggregatesOutput>;
}

export type { ListProjectAggregatesInput, ListProjectAggregatesOutput } from "../dto/aggregate.dto";
