/**
 * RiskBadgeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskBadgeRepository Port
 *
 * DDD: Application port for riskbadgerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPartnerRiskBadgeInput, GetPartnerRiskBadgeOutput } from "../dto/risk-badge.dto";
export interface RiskBadgeRepository {
  getPartnerRiskBadge(input: GetPartnerRiskBadgeInput): Promise<GetPartnerRiskBadgeOutput>;
}

export type { GetPartnerRiskBadgeInput, GetPartnerRiskBadgeOutput } from "../dto/risk-badge.dto";
