/**
 * DeleteExternalLink handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { deleteExternalLink } from "@chatterisk/api-server/domains/external-links/handlers";
import type { ExternalLinksDDDDependencies } from "@chatterisk/api-server/domains/external-links";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { EXTERNALLINKS_USE_CASES } from "../__factories__/use-cases.js";

describe("DeleteExternalLink", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExternalLinksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExternalLinksDDDDependencies>(
      EXTERNALLINKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 204 on successful deletion", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    mockRequest.params = { linkId: entity.id };
    
    vi.spyOn(mockDeps.executeDeleteExternalLink, "execute").mockResolvedValue(undefined);

    await deleteExternalLink(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDeleteExternalLink.execute).toHaveBeenCalledWith(expect.objectContaining({ linkId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(204);
  });

});
