/**
 * GetExternalLink handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getExternalLink } from "@chatterisk/api-server/domains/external-links/handlers";
import type { ExternalLinksDDDDependencies } from "@chatterisk/api-server/domains/external-links";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { EXTERNALLINKS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetExternalLink", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExternalLinksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExternalLinksDDDDependencies>(
      EXTERNALLINKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetExternalLink, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { linkId: entity.id };

    await getExternalLink(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetExternalLink.execute).toHaveBeenCalledWith(expect.objectContaining({ linkId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { linkId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetExternalLink, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getExternalLink(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
