/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-external-link.handler.test.js";
export * from "./delete-external-link.handler.test.js";
export * from "./get-external-link.handler.test.js";
export * from "./list-external-links.handler.test.js";
