/**
 * DeleteExternalLink DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { DeleteExternalLinkParams } from "@chatterisk/core/external-links";

export function createDeleteExternalLinkRequest(overrides: Partial<DeleteExternalLinkParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
