/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @chatterisk/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@chatterisk/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@chatterisk/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@chatterisk/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@chatterisk/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@chatterisk/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _aggregates from "./aggregates/index.js";
import * as _alerts from "./alerts/index.js";
import * as _comments from "./comments/index.js";
import * as _dossiers from "./dossiers/index.js";
import * as _externalLinks from "./external-links/index.js";
import * as _identity from "./identity/index.js";
import * as _projects from "./projects/index.js";

// Export as namespaces
export const _shared = __shared;
export const aggregates = _aggregates;
export const alerts = _alerts;
export const comments = _comments;
export const dossiers = _dossiers;
export const externalLinks = _externalLinks;
export const identity = _identity;
export const projects = _projects;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@chatterisk/core"; activity.types.*
//   - Direct exports: import * from "@chatterisk/core/activity/types/index.js"
//   - Direct exports: import * from "@chatterisk/core/activity/repositories/index.js"
//   - Direct exports: import * from "@chatterisk/core/activity/models/index.js"
//   - Direct exports: import * from "@chatterisk/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Aggregates Service
export { schemas as AggregatesSchemas } from "./aggregates/schemas/aggregates.schemas.js";

// Alerts Service
export { schemas as AlertsSchemas } from "./alerts/schemas/alerts.schemas.js";

// Comments Service
export { schemas as CommentsSchemas } from "./comments/schemas/comments.schemas.js";

// Dossiers Service
export { schemas as DossiersSchemas } from "./dossiers/schemas/dossiers.schemas.js";

// ExternalLinks Service
export { schemas as ExternalLinksSchemas } from "./external-links/schemas/external-links.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Projects Service
export { schemas as ProjectsSchemas } from "./projects/schemas/projects.schemas.js";

