/**
 * Comments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Comments Domain Module - Composition root
 *
 * DDD: Composition root for comments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BotRulingRepositoryAdapter,
  CommentRepositoryAdapter,
  RedactRepositoryAdapter,
  RetentionRepositoryAdapter,
  RunRepositoryAdapter,
} from "@chatterisk/adapters/comments";
import { getIdGeneratorService } from "@chatterisk/adapters";
import type { AdapterDynamoDBClient } from "@chatterisk/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApplyCommentBotRuling,
  ExecuteGetComment,
  ExecuteGetCommentRetentionPolicy,
  ExecuteIngestComment,
  ExecuteListBotRulings,
  ExecuteListProjectComments,
  ExecuteRedactCommentPii,
  ExecuteRunCommentRetentionJob,
  ExecuteUpdateCommentRetentionPolicy,
} from "@chatterisk/services/comments/usecases";
// Ports (interfaces)
import type {
  BotRulingRepository,
  CommentRepository,
  RedactRepository,
  RetentionRepository,
  RunRepository,
} from "@chatterisk/services/comments/ports";

export interface CommentsDomainModule {
  repos: {
    botRulings: BotRulingRepository;
    comments: CommentRepository;
    redacts: RedactRepository;
    retentions: RetentionRepository;
    runs: RunRepository;
  };
  useCases: {
    botRulings: {
      get: ExecuteApplyCommentBotRuling;
      list: ExecuteListBotRulings;
    };
    comments: {
      get: ExecuteGetComment;
      list: ExecuteListProjectComments;
      create: ExecuteIngestComment;
    };
    redacts: {
      get: ExecuteRedactCommentPii;
    };
    retentions: {
      get: ExecuteGetCommentRetentionPolicy;
      update: ExecuteUpdateCommentRetentionPolicy;
    };
    runs: {
      create: ExecuteRunCommentRetentionJob;
    };
  };
}

export function buildCommentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CommentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      botRulings?: BotRulingRepository;
      comments?: CommentRepository;
      redacts?: RedactRepository;
      retentions?: RetentionRepository;
      runs?: RunRepository;
    } = {};

    obj.botRulings = new BotRulingRepositoryAdapter(dynamoClient);
    obj.comments = new CommentRepositoryAdapter(dynamoClient);
    obj.redacts = new RedactRepositoryAdapter(dynamoClient);
    obj.retentions = new RetentionRepositoryAdapter(dynamoClient);
    obj.runs = new RunRepositoryAdapter(dynamoClient);
    return {
      botRulings: obj.botRulings!,
      comments: obj.comments!,
      redacts: obj.redacts!,
      retentions: obj.retentions!,
      runs: obj.runs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    botRulings: {
      get: new ExecuteApplyCommentBotRuling(executionContext, idGenerator, repos.botRulings),
      list: new ExecuteListBotRulings(executionContext, idGenerator, repos.botRulings),
    },
    comments: {
      get: new ExecuteGetComment(executionContext, idGenerator, repos.comments),
      list: new ExecuteListProjectComments(executionContext, idGenerator, repos.comments),
      create: new ExecuteIngestComment(executionContext, idGenerator, repos.comments),
    },
    redacts: {
      get: new ExecuteRedactCommentPii(executionContext, idGenerator, repos.redacts),
    },
    retentions: {
      get: new ExecuteGetCommentRetentionPolicy(executionContext, idGenerator, repos.retentions),
      update: new ExecuteUpdateCommentRetentionPolicy(executionContext, idGenerator, repos.retentions),
    },
    runs: {
      create: new ExecuteRunCommentRetentionJob(executionContext, idGenerator, repos.runs),
    },
  };
  return { repos, useCases: useCases as CommentsDomainModule["useCases"] };
}
