/**
 * Repository interface for BotRuling
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  BotRulingEntity
} from "../models/bot-ruling.entity.js";
import type {
  ListBotRulingsParams,
  BotRuling
} from "../types/index.js";
/**
 * BotRulingRepository Interface
 */
export interface BotRulingRepository extends CreateReadRepository<BotRulingEntity, BotRuling, string, ListBotRulingsParams> {

}
