/**
 * Alerts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alerts Domain Module - Composition root
 *
 * DDD: Composition root for alerts domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  AlertPolicyRepositoryAdapter,
  AlertRepositoryAdapter,
  SnoozeRepositoryAdapter,
} from "@chatterisk/adapters/alerts";
import { getIdGeneratorService } from "@chatterisk/adapters";
import type { AdapterDynamoDBClient } from "@chatterisk/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeAlert,
  ExecuteCreateAlertPolicy,
  ExecuteGetAlertPolicy,
  ExecuteListAlertPolicies,
  ExecuteListRiskAlerts,
  ExecuteSnoozeAlert,
  ExecuteUpdateAlertPolicy,
} from "@chatterisk/services/alerts/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  AlertPolicyRepository,
  AlertRepository,
  SnoozeRepository,
} from "@chatterisk/services/alerts/ports";

export interface AlertsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    alertPolicies: AlertPolicyRepository;
    alerts: AlertRepository;
    snoozes: SnoozeRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeAlert;
    };
    alertPolicies: {
      create: ExecuteCreateAlertPolicy;
      get: ExecuteGetAlertPolicy;
      list: ExecuteListAlertPolicies;
      update: ExecuteUpdateAlertPolicy;
    };
    alerts: {
      list: ExecuteListRiskAlerts;
    };
    snoozes: {
      get: ExecuteSnoozeAlert;
    };
  };
}

export function buildAlertsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AlertsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      alertPolicies?: AlertPolicyRepository;
      alerts?: AlertRepository;
      snoozes?: SnoozeRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.alertPolicies = new AlertPolicyRepositoryAdapter(dynamoClient);
    obj.alerts = new AlertRepositoryAdapter(dynamoClient);
    obj.snoozes = new SnoozeRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      alertPolicies: obj.alertPolicies!,
      alerts: obj.alerts!,
      snoozes: obj.snoozes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeAlert(executionContext, idGenerator, repos.acknowledges),
    },
    alertPolicies: {
      create: new ExecuteCreateAlertPolicy(executionContext, idGenerator, repos.alertPolicies),
      get: new ExecuteGetAlertPolicy(executionContext, idGenerator, repos.alertPolicies),
      list: new ExecuteListAlertPolicies(executionContext, idGenerator, repos.alertPolicies),
      update: new ExecuteUpdateAlertPolicy(executionContext, idGenerator, repos.alertPolicies),
    },
    alerts: {
      list: new ExecuteListRiskAlerts(executionContext, idGenerator, repos.alerts),
    },
    snoozes: {
      get: new ExecuteSnoozeAlert(executionContext, idGenerator, repos.snoozes),
    },
  };
  return { repos, useCases: useCases as AlertsDomainModule["useCases"] };
}
