/**
 * AlertPolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AlertPolicyEntity } from "@chatterisk/core/alerts/models/index.js";
import { alertsSchemas } from "@chatterisk/core/alerts";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "alt";

export function createAlertPolicy(overrides: Partial<AlertPolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    policyId: overrides.policyId ?? `plc_${ulid().toLowerCase()}`,
    threshold: overrides.threshold ?? faker.number.int(),
    workspaceId: overrides.workspaceId ?? faker.string.uuid(),
    ...overrides,
  };

  return alertsSchemas.AlertPolicy.parse(raw);
}

export function alertPolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAlertPolicy(overrides));
}
