/**
 * Routes for ExternalLink
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: external-links
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createExternalLink, deleteExternalLink, getExternalLink, listExternalLinks } from "../handlers/external-link.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function externalLinkRoutes(fastify: FastifyInstance) {
  // POST /v1/external-links (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/external-links",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExternalLinksDependenciesForRequest();
        await createExternalLink(request, reply, deps);
      });
    }
  );


  // GET /v1/external-links (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/external-links",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExternalLinksDependenciesForRequest();
        await listExternalLinks(request, reply, deps);
      });
    }
  );


  // DELETE /v1/external-links/{linkId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/external-links/:linkId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { linkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExternalLinksDependenciesForRequest();
        await deleteExternalLink(request, reply, deps);
      });
    }
  );


  // GET /v1/external-links/{linkId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/external-links/:linkId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { linkId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getExternalLinksDependenciesForRequest();
        await getExternalLink(request, reply, deps);
      });
    }
  );


}
