/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the comments domain.
 * Use these factories in tests to create test data.
 */

export { createBotRuling } from "./bot-ruling/entity/bot-ruling.entity.factory.js";
export { createCreateRedactRequest } from "./redact/dto/create-redact.dto.factory.js";
