/**
 * ListBotRuling DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListBotRulingsParams } from "@chatterisk/core/comments";

export function createListBotRulingRequest(overrides: Partial<ListBotRulingsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
