/**
 * BotRuling DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BotRuling DTOs
 *
 * DDD: Application DTOs for BotRuling use cases.
 */

import type { ApplyCommentBotRulingParams, ApplyCommentBotRulingRequestInput, ListBotRulingsParams } from "@chatterisk/core/comments/types";

export type ApplyCommentBotRulingInput = ApplyCommentBotRulingParams & ApplyCommentBotRulingRequestInput;

export type ListBotRulingsInput = ListBotRulingsParams;

export type ApplyCommentBotRulingOutput = {};

export type ListBotRulingsOutput = {};
