/**
 * Comment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Comment DTOs
 *
 * DDD: Application DTOs for Comment use cases.
 */

import type { GetCommentParams, IngestCommentParams, IngestCommentRequestInput, ListProjectCommentsParams } from "@chatterisk/core/comments/types";

export type ListProjectCommentsInput = ListProjectCommentsParams;

export type IngestCommentInput = IngestCommentParams & IngestCommentRequestInput;

export type GetCommentInput = GetCommentParams;

export type ListProjectCommentsOutput = {};

export type IngestCommentOutput = {};

export type GetCommentOutput = {};
