/**
 * Redact DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Redact DTOs
 *
 * DDD: Application DTOs for Redact use cases.
 */

import type { RedactCommentPiiParams } from "@chatterisk/core/comments/types";

export type RedactCommentPiiInput = RedactCommentPiiParams;

export type RedactCommentPiiOutput = {};
