/**
 * Retention DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Retention DTOs
 *
 * DDD: Application DTOs for Retention use cases.
 */

import type { UpdateCommentRetentionPolicyRequestInput } from "@chatterisk/core/comments/types";

export type GetCommentRetentionPolicyInput = {};

export type UpdateCommentRetentionPolicyInput = UpdateCommentRetentionPolicyRequestInput;

export type GetCommentRetentionPolicyOutput = {};

export type UpdateCommentRetentionPolicyOutput = {};
