/**
 * Run DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Run DTOs
 *
 * DDD: Application DTOs for Run use cases.
 */

export type RunCommentRetentionJobInput = {};

export type RunCommentRetentionJobOutput = {};
