/**
 * ExecuteGetComment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetComment Use Case
 *
 * DDD: Application use case for get Comment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCommentInput, GetCommentOutput } from "../dto/comment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { CommentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetComment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly comment: CommentRepository
  ) {}

  async execute(input: GetCommentInput): Promise<GetCommentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).commentId) {
      throw new ValidationError("commentId is required");
    }
    const commentId = (input as any).commentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.comment.getComment({ commentId: commentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${commentId}`);
    }

    return entity as GetCommentOutput;
  }
}
