/**
 * ExecuteListProjectComments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListProjectComments Use Case
 *
 * DDD: Application use case for list Comment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListProjectCommentsInput, ListProjectCommentsOutput } from "../dto/comment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { CommentRepository } from "../ports";

export class ExecuteListProjectComments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly comment: CommentRepository
  ) {}

  async execute(input: ListProjectCommentsInput): Promise<ListProjectCommentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.comment.listProjectComments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListProjectCommentsOutput;
  }
}
