/**
 * ExecuteApplyCommentBotRuling - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApplyCommentBotRuling Use Case
 *
 * DDD: Application use case for get BotRuling.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApplyCommentBotRulingInput, ApplyCommentBotRulingOutput } from "../dto/bot-ruling.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { BotRulingRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteApplyCommentBotRuling {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly botRuling: BotRulingRepository
  ) {}

  async execute(input: ApplyCommentBotRulingInput): Promise<ApplyCommentBotRulingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: kind, note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).commentId) {
      throw new ValidationError("commentId is required");
    }
    const commentId = (input as any).commentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.botRuling.applyCommentBotRuling({ commentId: commentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${commentId}`);
    }

    return entity as ApplyCommentBotRulingOutput;
  }
}
