/**
 * ExecuteIngestComment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestComment Use Case
 *
 * DDD: Application use case for get Comment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestCommentInput, IngestCommentOutput } from "../dto/comment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { CommentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestComment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly comment: CommentRepository
  ) {}

  async execute(input: IngestCommentInput): Promise<IngestCommentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: channel, externalId, publishedAt, text
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.comment.ingestComment({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${projectId}`);
    }

    return entity as IngestCommentOutput;
  }
}
