/**
 * ExecuteRunCommentRetentionJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRunCommentRetentionJob Use Case
 *
 * DDD: Application use case for create Run.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RunCommentRetentionJobInput, RunCommentRetentionJobOutput } from "../dto/run.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { RunRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRunCommentRetentionJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly run: RunRepository
  ) {}

  async execute(input: RunCommentRetentionJobInput): Promise<RunCommentRetentionJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (comments domain)
    const entityId = this.idGenerator.cmtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.run.runCommentRetentionJob({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RunCommentRetentionJobOutput;
  }
}
