/**
 * ExecuteListBotRulings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBotRulings Use Case
 *
 * DDD: Application use case for list BotRuling.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBotRulingsInput, ListBotRulingsOutput } from "../dto/bot-ruling.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { BotRulingRepository } from "../ports";

export class ExecuteListBotRulings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly botRuling: BotRulingRepository
  ) {}

  async execute(input: ListBotRulingsInput): Promise<ListBotRulingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cmtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.botRuling.listBotRulings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBotRulingsOutput;
  }
}
