/**
 * AlertPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AlertPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AlertPolicyRepository,
} from "@chatterisk/services/alerts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AlertPolicyRepositoryDdb } from "./alert-policy-repository.ddb.js";

/**
 * AlertPolicyRepositoryAdapter
 *
 * Implements AlertPolicyRepository port for infrastructure layer.
 */
export class AlertPolicyRepositoryAdapter implements AlertPolicyRepository {
  private readonly ddb: AlertPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AlertPolicyRepositoryDdb(this.dynamoClient);
  }

  async listAlertPolicies(input: Parameters<AlertPolicyRepository['listAlertPolicies']>[0]): Promise<Awaited<ReturnType<AlertPolicyRepository['listAlertPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAlertPolicies(input);
  }

  async createAlertPolicy(input: Parameters<AlertPolicyRepository['createAlertPolicy']>[0]): Promise<Awaited<ReturnType<AlertPolicyRepository['createAlertPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAlertPolicy(input);
  }

  async getAlertPolicy(input: Parameters<AlertPolicyRepository['getAlertPolicy']>[0]): Promise<Awaited<ReturnType<AlertPolicyRepository['getAlertPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAlertPolicy(input);
  }

  async updateAlertPolicy(input: Parameters<AlertPolicyRepository['updateAlertPolicy']>[0]): Promise<Awaited<ReturnType<AlertPolicyRepository['updateAlertPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAlertPolicy(input);
  }
}
