/**
 * SnoozeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnoozeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SnoozeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SnoozeRepository,
} from "@chatterisk/services/alerts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SnoozeRepositoryDdb } from "./snooze-repository.ddb.js";

/**
 * SnoozeRepositoryAdapter
 *
 * Implements SnoozeRepository port for infrastructure layer.
 */
export class SnoozeRepositoryAdapter implements SnoozeRepository {
  private readonly ddb: SnoozeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SnoozeRepositoryDdb(this.dynamoClient);
  }

  async snoozeAlert(input: Parameters<SnoozeRepository['snoozeAlert']>[0]): Promise<Awaited<ReturnType<SnoozeRepository['snoozeAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.snoozeAlert(input);
  }
}
