/**
 * CommentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CommentRepository Port
 *
 * DDD: Application port for commentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCommentInput, GetCommentOutput, IngestCommentInput, IngestCommentOutput, ListProjectCommentsInput, ListProjectCommentsOutput } from "../dto/comment.dto";
export interface CommentRepository {
  listProjectComments(input: ListProjectCommentsInput): Promise<ListProjectCommentsOutput>;
  ingestComment(input: IngestCommentInput): Promise<IngestCommentOutput>;
  getComment(input: GetCommentInput): Promise<GetCommentOutput>;
}

export type { GetCommentInput, GetCommentOutput, IngestCommentInput, IngestCommentOutput, ListProjectCommentsInput, ListProjectCommentsOutput } from "../dto/comment.dto";
