/**
 * RedactRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RedactRepository Port
 *
 * DDD: Application port for redactrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RedactCommentPiiInput, RedactCommentPiiOutput } from "../dto/redact.dto";
export interface RedactRepository {
  redactCommentPii(input: RedactCommentPiiInput): Promise<RedactCommentPiiOutput>;
}

export type { RedactCommentPiiInput, RedactCommentPiiOutput } from "../dto/redact.dto";
