/**
 * RetentionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetentionRepository Port
 *
 * DDD: Application port for retentionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCommentRetentionPolicyInput, GetCommentRetentionPolicyOutput, UpdateCommentRetentionPolicyInput, UpdateCommentRetentionPolicyOutput } from "../dto/retention.dto";
export interface RetentionRepository {
  getCommentRetentionPolicy(input: GetCommentRetentionPolicyInput): Promise<GetCommentRetentionPolicyOutput>;
  updateCommentRetentionPolicy(input: UpdateCommentRetentionPolicyInput): Promise<UpdateCommentRetentionPolicyOutput>;
}

export type { GetCommentRetentionPolicyInput, GetCommentRetentionPolicyOutput, UpdateCommentRetentionPolicyInput, UpdateCommentRetentionPolicyOutput } from "../dto/retention.dto";
