/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAggregatesDomainModule } from "./aggregates/dependencies/aggregates-ddd.dependencies.js";
export { buildAlertsDomainModule } from "./alerts/dependencies/alerts-ddd.dependencies.js";
export { buildCommentsDomainModule } from "./comments/dependencies/comments-ddd.dependencies.js";
export { buildDossiersDomainModule } from "./dossiers/dependencies/dossiers-ddd.dependencies.js";
export { buildExternalLinksDomainModule } from "./external-links/dependencies/external-links-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildProjectsDomainModule } from "./projects/dependencies/projects-ddd.dependencies.js";

// Export all domain dependency types
export type { AggregatesDomainModule } from "./aggregates/dependencies/aggregates-ddd.dependencies.js";
export type { AlertsDomainModule } from "./alerts/dependencies/alerts-ddd.dependencies.js";
export type { CommentsDomainModule } from "./comments/dependencies/comments-ddd.dependencies.js";
export type { DossiersDomainModule } from "./dossiers/dependencies/dossiers-ddd.dependencies.js";
export type { ExternalLinksDomainModule } from "./external-links/dependencies/external-links-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { ProjectsDomainModule } from "./projects/dependencies/projects-ddd.dependencies.js";
