/**
 * Routes for AlertPolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAlertPolicy, getAlertPolicy, listAlertPolicies, updateAlertPolicy } from "../handlers/alert-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function alertPolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/alert-policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/alert-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlertsDependenciesForRequest();
        await createAlertPolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/alert-policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/alert-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlertsDependenciesForRequest();
        await listAlertPolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/alert-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/alert-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlertsDependenciesForRequest();
        await getAlertPolicy(request, reply, deps);
      });
    }
  );


  // PATCH /v1/alert-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/alert-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAlertsDependenciesForRequest();
        await updateAlertPolicy(request, reply, deps);
      });
    }
  );


}
