/**
 * Handlers for AlertPolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertsDomainModule } from "../dependencies/alerts-ddd.dependencies.js";
import type { CreateAlertPolicyInput, GetAlertPolicyInput, ListAlertPoliciesInput, UpdateAlertPolicyInput } from "@chatterisk/services/alerts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/alert-policies
 * Operation: listAlertPolicies
 */
export async function listAlertPolicies(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {};
  const result = await deps.useCases.alertPolicies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/alert-policies
 * Operation: createAlertPolicy
 */
export async function createAlertPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as CreateAlertPolicyInput;
  const result = await deps.useCases.alertPolicies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/alert-policies/{policyId}
 * Operation: getAlertPolicy
 */
export async function getAlertPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    policyId: request.params.policyId,
  } as GetAlertPolicyInput;
  const result = await deps.useCases.alertPolicies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/alert-policies/{policyId}
 * Operation: updateAlertPolicy
 */
export async function updateAlertPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    policyId: request.params.policyId,
    ...(request.body ?? {}),
  } as UpdateAlertPolicyInput;
  const result = await deps.useCases.alertPolicies.update.execute(input);
  return reply.code(200).send(result);
}


