/**
 * Handlers for Snooze
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AlertsDomainModule } from "../dependencies/alerts-ddd.dependencies.js";
import type { SnoozeAlertInput } from "@chatterisk/services/alerts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/alerts/{alertId}/snooze
 * Operation: snoozeAlert
 */
export async function snoozeAlert(
  request: FastifyRequest<{ Params: { alertId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AlertsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    alertId: request.params.alertId,
    ...(request.body ?? {}),
  } as SnoozeAlertInput;
  const result = await deps.useCases.snoozes.get.execute(input);
  return reply.code(200).send(result);
}


