/**
 * BotRuling Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/comments.openapi.types.js";
import { schemas } from "../schemas/comments.schemas.js";

/**
 * Entity: BotRulingEntity
 * Description: Represents the BotRuling domain model.
 * Source: schemas.BotRuling
 * Type: Domain Entity (API)
 */
export const BotRulingEntitySchema = schemas.BotRuling;
export type BotRulingEntity = components["schemas"]["BotRuling"];
