/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Comments Domain Use Cases
 * 
 * List of all use case names for the comments domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const COMMENTS_USE_CASES = [
  "executeApplyCommentBotRuling",
  "executeGetComment",
  "executeGetCommentRetentionPolicy",
  "executeIngestComment",
  "executeListBotRulings",
  "executeListProjectComments",
  "executeRedactCommentPii",
  "executeRunCommentRetentionJob",
  "executeUpdateCommentRetentionPolicy"
] as const;
