/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@chatterisk/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@chatterisk/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@chatterisk/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _aggregates from "./aggregates/index.js";
import * as _alerts from "./alerts/index.js";
import * as _comments from "./comments/index.js";
import * as _dossiers from "./dossiers/index.js";
import * as _externalLinks from "./external-links/index.js";
import * as _identity from "./identity/index.js";
import * as _projects from "./projects/index.js";

// Export as namespaces
export const aggregates = _aggregates;
export const alerts = _alerts;
export const comments = _comments;
export const dossiers = _dossiers;
export const externalLinks = _externalLinks;
export const identity = _identity;
export const projects = _projects;
