/**
 * ExecuteGetLatestAggregate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetLatestAggregate Use Case
 *
 * DDD: Application use case for get Latest.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetLatestAggregateInput, GetLatestAggregateOutput } from "../dto/latest.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { LatestRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetLatestAggregate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly latest: LatestRepository
  ) {}

  async execute(input: GetLatestAggregateInput): Promise<GetLatestAggregateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aggId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.latest.getLatestAggregate({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetLatestAggregateOutput;
  }
}
