/**
 * ExecuteGetPartnerRiskBadge - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPartnerRiskBadge Use Case
 *
 * DDD: Application use case for get RiskBadge.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPartnerRiskBadgeInput, GetPartnerRiskBadgeOutput } from "../dto/risk-badge.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { RiskBadgeRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetPartnerRiskBadge {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly riskBadge: RiskBadgeRepository
  ) {}

  async execute(input: GetPartnerRiskBadgeInput): Promise<GetPartnerRiskBadgeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aggId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.riskBadge.getPartnerRiskBadge({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetPartnerRiskBadgeOutput;
  }
}
