/**
 * BotRulingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BotRulingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BotRulingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BotRulingRepository,
} from "@chatterisk/services/comments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BotRulingRepositoryDdb } from "./bot-ruling-repository.ddb.js";

/**
 * BotRulingRepositoryAdapter
 *
 * Implements BotRulingRepository port for infrastructure layer.
 */
export class BotRulingRepositoryAdapter implements BotRulingRepository {
  private readonly ddb: BotRulingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BotRulingRepositoryDdb(this.dynamoClient);
  }

  async applyCommentBotRuling(input: Parameters<BotRulingRepository['applyCommentBotRuling']>[0]): Promise<Awaited<ReturnType<BotRulingRepository['applyCommentBotRuling']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.applyCommentBotRuling(input);
  }

  async listBotRulings(input: Parameters<BotRulingRepository['listBotRulings']>[0]): Promise<Awaited<ReturnType<BotRulingRepository['listBotRulings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBotRulings(input);
  }
}
