/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./bot-ruling-repository.ddb.js";
export * from "./comment-repository.ddb.js";
export * from "./redact-repository.ddb.js";
export * from "./retention-repository.ddb.js";
export * from "./run-repository.ddb.js";
export * from "./bot-ruling-repository.adapter.js";
export * from "./comment-repository.adapter.js";
export * from "./redact-repository.adapter.js";
export * from "./retention-repository.adapter.js";
export * from "./run-repository.adapter.js";
