/**
 * RedactRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RedactRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RedactRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RedactRepository,
} from "@chatterisk/services/comments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RedactRepositoryDdb } from "./redact-repository.ddb.js";

/**
 * RedactRepositoryAdapter
 *
 * Implements RedactRepository port for infrastructure layer.
 */
export class RedactRepositoryAdapter implements RedactRepository {
  private readonly ddb: RedactRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RedactRepositoryDdb(this.dynamoClient);
  }

  async redactCommentPii(input: Parameters<RedactRepository['redactCommentPii']>[0]): Promise<Awaited<ReturnType<RedactRepository['redactCommentPii']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.redactCommentPii(input);
  }
}
