/**
 * RetentionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetentionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RetentionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RetentionRepository,
} from "@chatterisk/services/comments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RetentionRepositoryDdb } from "./retention-repository.ddb.js";

/**
 * RetentionRepositoryAdapter
 *
 * Implements RetentionRepository port for infrastructure layer.
 */
export class RetentionRepositoryAdapter implements RetentionRepository {
  private readonly ddb: RetentionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RetentionRepositoryDdb(this.dynamoClient);
  }

  async getCommentRetentionPolicy(input: Parameters<RetentionRepository['getCommentRetentionPolicy']>[0]): Promise<Awaited<ReturnType<RetentionRepository['getCommentRetentionPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCommentRetentionPolicy(input);
  }

  async updateCommentRetentionPolicy(input: Parameters<RetentionRepository['updateCommentRetentionPolicy']>[0]): Promise<Awaited<ReturnType<RetentionRepository['updateCommentRetentionPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateCommentRetentionPolicy(input);
  }
}
