/**
 * RunRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RunRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RunRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RunRepository,
} from "@chatterisk/services/comments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RunRepositoryDdb } from "./run-repository.ddb.js";

/**
 * RunRepositoryAdapter
 *
 * Implements RunRepository port for infrastructure layer.
 */
export class RunRepositoryAdapter implements RunRepository {
  private readonly ddb: RunRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RunRepositoryDdb(this.dynamoClient);
  }

  async runCommentRetentionJob(input: Parameters<RunRepository['runCommentRetentionJob']>[0]): Promise<Awaited<ReturnType<RunRepository['runCommentRetentionJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.runCommentRetentionJob(input);
  }
}
