/**
 * CreateDossier handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dossiers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createDossier } from "@chatterisk/api-server/domains/dossiers/handlers";
import type { DossiersDDDDependencies } from "@chatterisk/api-server/domains/dossiers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@chatterisk/tests/shared";
import { DOSSIERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateDossier", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DossiersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DossiersDDDDependencies>(
      DOSSIERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateDossier, "execute").mockResolvedValue(useCaseResult);

    await createDossier(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateDossier.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
