/**
 * GetLatest DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLatestAggregateParams } from "@chatterisk/core/aggregates";

export function createGetLatestRequest(overrides: Partial<GetLatestAggregateParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
