/**
 * AlertPolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertPolicyRepository Port
 *
 * DDD: Application port for alertpolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAlertPolicyInput, CreateAlertPolicyOutput, GetAlertPolicyInput, GetAlertPolicyOutput, ListAlertPoliciesInput, ListAlertPoliciesOutput, UpdateAlertPolicyInput, UpdateAlertPolicyOutput } from "../dto/alert-policy.dto";
export interface AlertPolicyRepository {
  listAlertPolicies(input: ListAlertPoliciesInput): Promise<ListAlertPoliciesOutput>;
  createAlertPolicy(input: CreateAlertPolicyInput): Promise<CreateAlertPolicyOutput>;
  getAlertPolicy(input: GetAlertPolicyInput): Promise<GetAlertPolicyOutput>;
  updateAlertPolicy(input: UpdateAlertPolicyInput): Promise<UpdateAlertPolicyOutput>;
}

export type { CreateAlertPolicyInput, CreateAlertPolicyOutput, GetAlertPolicyInput, GetAlertPolicyOutput, ListAlertPoliciesInput, ListAlertPoliciesOutput, UpdateAlertPolicyInput, UpdateAlertPolicyOutput } from "../dto/alert-policy.dto";
