/**
 * SnoozeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnoozeRepository Port
 *
 * DDD: Application port for snoozerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SnoozeAlertInput, SnoozeAlertOutput } from "../dto/snooze.dto";
export interface SnoozeRepository {
  snoozeAlert(input: SnoozeAlertInput): Promise<SnoozeAlertOutput>;
}

export type { SnoozeAlertInput, SnoozeAlertOutput } from "../dto/snooze.dto";
