/**
 * Handlers for Latest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: aggregates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AggregatesDomainModule } from "../dependencies/aggregates-ddd.dependencies.js";
import type { GetLatestAggregateInput } from "@chatterisk/services/aggregates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/aggregates/latest
 * Operation: getLatestAggregate
 */
export async function getLatestAggregate(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { contractAddress?: string | string[], projectId?: string | string[], window?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AggregatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as GetLatestAggregateInput;
  const result = await deps.useCases.latests.get.execute(input);
  return reply.code(200).send(result);
}


