/**
 * Handlers for BotRuling
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CommentsDomainModule } from "../dependencies/comments-ddd.dependencies.js";
import type { ApplyCommentBotRulingInput, ListBotRulingsInput } from "@chatterisk/services/comments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/comments/{commentId}/bot-ruling
 * Operation: applyCommentBotRuling
 */
export async function applyCommentBotRuling(
  request: FastifyRequest<{ Params: { commentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    commentId: request.params.commentId,
    ...(request.body ?? {}),
  } as ApplyCommentBotRulingInput;
  const result = await deps.useCases.botRulings.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/bot-rulings
 * Operation: listBotRulings
 */
export async function listBotRulings(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], projectId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.query ?? {}),
  } as ListBotRulingsInput;
  const result = await deps.useCases.botRulings.list.execute(input);
  return reply.code(200).send(result);
}


