/**
 * Handlers for Comment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CommentsDomainModule } from "../dependencies/comments-ddd.dependencies.js";
import type { GetCommentInput, IngestCommentInput, ListProjectCommentsInput } from "@chatterisk/services/comments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/projects/{projectId}/comments
 * Operation: listProjectComments
 */
export async function listProjectComments(
  request: FastifyRequest<{ Params: { projectId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    projectId: request.params.projectId,
    ...(request.query ?? {}),
  } as ListProjectCommentsInput;
  const result = await deps.useCases.comments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/projects/{projectId}/comments
 * Operation: ingestComment
 */
export async function ingestComment(
  request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    projectId: request.params.projectId,
    ...(request.body ?? {}),
  } as IngestCommentInput;
  const result = await deps.useCases.comments.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/comments/{commentId}
 * Operation: getComment
 */
export async function getComment(
  request: FastifyRequest<{ Params: { commentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    commentId: request.params.commentId,
  } as GetCommentInput;
  const result = await deps.useCases.comments.get.execute(input);
  return reply.code(200).send(result);
}


