/**
 * Handlers for Redact
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CommentsDomainModule } from "../dependencies/comments-ddd.dependencies.js";
import type { RedactCommentPiiInput } from "@chatterisk/services/comments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/comments/{commentId}/redact
 * Operation: redactCommentPii
 */
export async function redactCommentPii(
  request: FastifyRequest<{ Params: { commentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    commentId: request.params.commentId,
  } as RedactCommentPiiInput;
  const result = await deps.useCases.redacts.get.execute(input);
  return reply.code(200).send(result);
}


