/**
 * Handlers for Retention
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CommentsDomainModule } from "../dependencies/comments-ddd.dependencies.js";
import type { GetCommentRetentionPolicyInput, UpdateCommentRetentionPolicyInput } from "@chatterisk/services/comments";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/comments/retention
 * Operation: getCommentRetentionPolicy
 */
export async function getCommentRetentionPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {};
  const result = await deps.useCases.retentions.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/comments/retention
 * Operation: updateCommentRetentionPolicy
 */
export async function updateCommentRetentionPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CommentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    ...(request.body ?? {}),
  } as UpdateCommentRetentionPolicyInput;
  const result = await deps.useCases.retentions.update.execute(input);
  return reply.code(200).send(result);
}


