/**
 * BotRuling Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: comments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { BotRulingEntity } from "@chatterisk/core/comments/models/index.js";
import { commentsSchemas } from "@chatterisk/core/comments";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmt";

export function createBotRuling(overrides: Partial<BotRulingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    commentId: overrides.commentId ?? `cmt_${ulid().toLowerCase()}`,
    kind: overrides.kind ?? "bot_suspect",
    rulingId: overrides.rulingId ?? `bot_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return commentsSchemas.BotRuling.parse(raw);
}

export function botRulingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBotRuling(overrides));
}
