/**
 * Handlers for Watch
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProjectsDomainModule } from "../dependencies/projects-ddd.dependencies.js";
import type { AddProjectToWatchlistInput, RemoveProjectFromWatchlistInput } from "@chatterisk/services/projects";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/projects/{projectId}/watch
 * Operation: addProjectToWatchlist
 */
export async function addProjectToWatchlist(
  request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    projectId: request.params.projectId,
  } as AddProjectToWatchlistInput;
  const result = await deps.useCases.watches.create.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for DELETE /v1/projects/{projectId}/watch
 * Operation: removeProjectFromWatchlist
 */
export async function removeProjectFromWatchlist(
  request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input = {
    projectId: request.params.projectId,
  } as RemoveProjectFromWatchlistInput;
  const result = await deps.useCases.watches.delete.execute(input);
  return reply.code(200).send(result);
}


