/**
 * AlertPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: alerts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertPolicy DTOs
 *
 * DDD: Application DTOs for AlertPolicy use cases.
 */

import type { CreateAlertPolicyRequestInput, GetAlertPolicyParams, UpdateAlertPolicyParams, UpdateAlertPolicyRequestInput } from "@chatterisk/core/alerts/types";

export type ListAlertPoliciesInput = {};

export type CreateAlertPolicyInput = CreateAlertPolicyRequestInput;

export type GetAlertPolicyInput = GetAlertPolicyParams;

export type UpdateAlertPolicyInput = UpdateAlertPolicyParams & UpdateAlertPolicyRequestInput;

export type ListAlertPoliciesOutput = {};

export type CreateAlertPolicyOutput = {};

export type GetAlertPolicyOutput = {};

export type UpdateAlertPolicyOutput = {};
