/**
 * CanDelete Policy - Business rule
 *
 * Generated by Policy Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CanDelete Policy
 *
 * DDD: Application policy for determining if delete operations are allowed.
 */

export const CanDelete = {
  allow(account: { status?: string }, _providerType: string): boolean {
    // Business rule: Allow if account is not disabled or blocked
    return account.status !== "disabled" && account.status !== "blocked";
  }
};
