/**
 * ExecuteRegisterRiskProject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterRiskProject Use Case
 *
 * DDD: Application use case for create Project.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterRiskProjectInput, RegisterRiskProjectOutput } from "../dto/project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { ProjectRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterRiskProject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly project: ProjectRepository
  ) {}

  async execute(input: RegisterRiskProjectInput): Promise<RegisterRiskProjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: aliases, contractAddress, name, ticker, watched
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (projects domain)
    const entityId = this.idGenerator.prjId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.project.registerRiskProject({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterRiskProjectOutput;
  }
}
