/**
 * ExecuteUpdateRiskProject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateRiskProject Use Case
 *
 * DDD: Application use case for update Project.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateRiskProjectInput, UpdateRiskProjectOutput } from "../dto/project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { ProjectRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateRiskProject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly project: ProjectRepository
  ) {}

  async execute(input: UpdateRiskProjectInput): Promise<UpdateRiskProjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.project.updateRiskProject({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateRiskProjectOutput;
  }
}
