/**
 * ExecuteListRiskProjects - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRiskProjects Use Case
 *
 * DDD: Application use case for list Project.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRiskProjectsInput, ListRiskProjectsOutput } from "../dto/project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { ProjectRepository } from "../ports";

export class ExecuteListRiskProjects {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly project: ProjectRepository
  ) {}

  async execute(input: ListRiskProjectsInput): Promise<ListRiskProjectsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.project.listRiskProjects({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRiskProjectsOutput;
  }
}
