/**
 * ExecuteRemoveProjectFromWatchlist - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRemoveProjectFromWatchlist Use Case
 *
 * DDD: Application use case for delete Watch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RemoveProjectFromWatchlistInput, RemoveProjectFromWatchlistOutput } from "../dto/watch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@chatterisk/services/_shared/index.js";
import type { WatchRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanDelete } from "../policies/can-delete.policy";
export class ExecuteRemoveProjectFromWatchlist {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly watch: WatchRepository
  ) {}

  async execute(input: RemoveProjectFromWatchlistInput): Promise<RemoveProjectFromWatchlistOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;
    // No get/list operation for this resource - call delete directly
    // Check policy
    if (!CanDelete.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Delete entity via repository (pass correlation ID for response meta)
    await this.watch.removeProjectFromWatchlist({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);

    return {} as RemoveProjectFromWatchlistOutput;
  }
}
